
GET http://localhost:8000/api/v1/product


###

POST http://localhost:8000/api/v1/product
Content-Type: application/json

{
    "prodId": 5,
    "name" : "Spring boot",
    "description" : "Refference book",
    "active" : true,
    "unitPrice" : 50.0,
    "unitsInStock" : 100
}



###

GET http://localhost:8000/api/v1/product




###

PUT http://localhost:8000/api/v1/product
Content-Type: application/json


###

DELETE http://localhost:8000/api/v1/product